server.port=8080
spring.application.name=clima-alert-service
spring.threads.virtual.enabled=true

weatherapi.base-url=http://api.weatherapi.com/v1
weatherapi.key=9c43b35f3e93469ab0015027260807

climalert.ubicacion=Buenos Aires
climalert.destinatarios=admin@clima.com,emergencias@clima.com,meteorologia@clima.com

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=1de591f6f900d1
spring.mail.password=07521af79bd0bc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true