server.port=8080
spring.application.name=clima-alert-service
spring.threads.virtual.enabled=true


climalert.ubicacion=CABA
climalert.destinatarios=admin@clima.com,emergencias@clima.com,meteorologia@clima.com

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true